repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-json
        exclude: caster-editor/tsconfig.json
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
    -   id: autoflake
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
-   repo: local
    hooks:
      - id: editor-lint
        name: "Linting editor"
        files: caster-editor
        language: system
        entry: /bin/sh -c "cd caster-editor && npm run lint"
      - id: frontend-lint
        name: "Linting frontend"
        files: caster-front
        language: system
        entry: /bin/sh -c "cd caster-front && npm run lint:ci -- --fix"
