version: '3.9'

services:
  backend:
    build: caster-back
    environment:
      - DJANGO_SU_USER=admin
      - DJANGO_SU_PASS=admin
    ports:
      - 8090:8000
    volumes:
      - ./caster-back/:/home/gencaster
      - ./data:/data
  
  frontend:
    build: caster-front
    ports:
      - 8080:8080
  
  voice:
    build: caster-voice
    env_file:
      - .secrets.env
    ports:
      - 8091:8080
    volumes:
      - ./data:/data

  sound:
    build: caster-sound
    ports:
      - 8060:8080
    volumes:
      - ./data:/data
