version: '3.9'

volumes:
  db:

services:
  database:
    image: amd64/postgres:14.5-alpine
    platform: linux/amd64
    env_file:
      - vars.env
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: caster-back
    platform: linux/amd64
    env_file:
      - vars.env
      - .secrets.env
    depends_on:
      - database
      - sound

  osc_backend:
    build: caster-back
    platform: linux/amd64
    env_file:
      - vars.env
      - .secrets.env
    command: ['python', 'osc_server.py']

  frontend:
    build: caster-front
    platform: linux/amd64
    depends_on:
      - backend
    ports:
      - 3000:3000

  sound:
    build:
      context: caster-sound
      args:
        - MAKE_JOBS=8
    platform: linux/amd64
    depends_on:
      - osc_backend
    env_file:
      - vars.env
# editor depends on different dockerfile for dev/prod
# so we declare it in its respective environment docker-compose file
