version: '3.9'

volumes:
  db:
services:
  database:
    image: postgres:14.2-alpine
    env_file:
      - vars.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    
  backend:
    build: caster-back
    env_file:
      - vars.env
    ports:
      - 8090:8000
    volumes:
      - ./caster-back/:/home/gencaster
      - ./data:/data
  
  frontend:
    build: caster-front
    ports:
      - 8080:8080
  
  voice:
    build: caster-voice
    env_file:
      - .secrets.env
    ports:
      - 8091:8080
    volumes:
      - ./data:/data

  sound:
    build: caster-sound
    ports:
      - 8060:8080
    volumes:
      - ./data:/data
