version: '3.9'

services:
  frontend:
      ports:
      - 3010:3000
  backend:
    env_file:
      - vars.env
      - vars.deploy.env
      - .secrets.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  osc_backend:
    ports:
      - 57130:57130

  sound:
    network_mode: host
