version: '3.9'

volumes:
  db:

services:
  database:
    image: postgres:14.2-alpine
    env_file:
      - vars.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: caster-back
    env_file:
      - vars.env
      - .secrets.env
    ports:
      - 8081:8000
    depends_on:
      - database
      - sound
    volumes:
      - ./caster-back/:/home/gencaster
      - ./data:/data
      - ./data:/home/gencaster/media

  osc_backend:
    build: caster-back
    env_file:
      - vars.env
      - .secrets.env
    # environment:
    #   - DJANGO_SETTINGS_MODULE
    volumes:
      - ./caster-back/:/home/gencaster
      - ./data:/data
      - ./data:/home/gencaster/media
    command: ["python", "osc_server.py"]

  frontend:
    build: caster-front
    volumes:
      # allows for hot reload on development server
      - ./caster-front/:/root/caster-front/
    depends_on:
      - backend
    ports:
      - 3000:3000

  sound:
    build: caster-sound
    ports:
      - 8090:8090  # debug frontend
      - 8088:8088  # janus server
      - 10000-10200:10000-10200
    depends_on:
      - osc_backend
    env_file:
      - vars.env
    volumes:
      - ./data:/data
      - ./caster-sound/sc.scd:/root/sc.scd
      - ./caster-sound/janus.jcfg:/opt/janus/etc/janus/janus.jcfg
      - ./caster-sound/janus.plugin.streaming.jcfg:/opt/janus/etc/janus/janus.plugin.streaming.jcfg
      - ./caster-sound/caster-sound.conf:/root/caster-sound.conf
